resources:
  - ../../base
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - cronjob.yaml

patches:
  - path: deployment_patch.yaml

configMapGenerator:
  - name: fulltext-annosync-config
    files:
      - annosync.user.properties
  - name: fulltext-indexing-config
    files:
      - indexing.user.properties
