# Port for local testing
server.port: 8084

spring:
  application:
    name: Fulltext API
  mvc:
    throw-exception-if-no-handler-found : true
server:
  error:
    include-message: always
    include-stacktrace: on_param
    include-exception: false

  compression:
    enabled: true
    min-response-size: 4096
    mime-types: application/json, application/ld+json, application/xml, text/html, text/xml, text/plain

management:
  endpoints:
    web:
      exposure:
        include: info, health

  info:
    env:
      enabled: true

  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

# Creates a redirect from /console to /swagger-ui/index.html
springdoc:
  swagger-ui:
    path: /console
  # Don't include Error controller in API commons
  paths-to-exclude: /error
