apiVersion: apps/v1
kind: Deployment
metadata:
  name: fulltext-api-deployment
spec:
  # selector.matchLabels is provided via Kustomize
  template:
    spec:
      containers:
        - name: fulltext-api
          image: europeana/fulltext-api
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/info
            initialDelaySeconds: 100
            periodSeconds: 60
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/info
            initialDelaySeconds: 100
            periodSeconds: 30
          volumeMounts:
            - name: config
              mountPath: "/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/fulltext.user.properties"
              readOnly: true
              subPath: fulltext.user.properties
      volumes:
        - name: config
          configMap:
            name: fulltext-api-config

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: fulltext-annosync-job
spec:
  # only one instance should run at a time
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 0
      template:
        spec:
          containers:
            - name: fulltext-annosync
              image: europeana/fulltext-annosync
              volumeMounts:
                - name: annosync-properties
                  mountPath: "/opt/app/config/annosync.user.properties"
                  readOnly: true
                  subPath: annosync.user.properties
              env:
                - name: SPRING_CONFIG_ADDITIONAL_LOCATION
                  value: "file:/opt/app/config/annosync.user.properties"
          restartPolicy: OnFailure
          volumes:
            - name: annosync-properties
              configMap:
                name: fulltext-annosync-config