apiVersion: apps/v1
kind: Deployment
metadata:
  name: fulltext-api-deployment
spec:
  # selector.matchLabels is provided via Kustomize
  template:
    spec:
      containers:
        - name: fulltext-api
          image: europeana/fulltext-api
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 50
            periodSeconds: 20
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 50
            periodSeconds: 20
          volumeMounts:
            - name: config
              mountPath: "/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/fulltext.user.properties"
              readOnly: true
              subPath: fulltext.user.properties
      volumes:
        - name: config
          configMap:
            name: fulltext-api-config
