resources:
  - deployment.yaml

commonLabels:
  app: fulltext-api

# expects files to be in the same directory
secretGenerator:
  - name: fulltext-api-secret
    files:
      - fulltext.user.properties
