resources:
  - ../../base
  - nodeport.yaml
#  uncomment to run annosync cronjob
#  - cronjob.yaml

patches:
  - target:
      kind: deployment
    path: deployment_patch.yaml

labels:
  - includeSelectors: true
    pairs:
      app: fulltext-api

# Uncomment to run annosync cronjob (also see cronjob.yaml)
# Requires annosync.user.properties file in the same directory
#configMapGenerator:
#  - name: fulltext-annosync-config
#    files:
#      - annosync.user.properties